### ISSUE TITLE
test fails from fresh installation

### ISSUE THREAD

**Issue by franchesoni** [chlsl/rrn-multisensor-multidate#1]
I created an environment with Python 3.10
`python -m venv env_rrn`
activated it
`source env_rrn/bin/activate`
cloned the repo and cd to it
`git clone https://github.com/chlsl/rrn-multisensor-multidate.git`
`cd rrn-multisensor-multidate/`
run the install script
`pip install .`
which gave
```
Processing /home/franchesoni/mine/creations/phd/projects/current/hyperspectral/rrn-multisensor-multidate
  Preparing metadata (setup.py) ... done
Collecting Pillow>=7.0.0
  Using cached Pillow-9.4.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.4 MB)
Collecting iio>=0.0.3
  Using cached iio-4.tar.gz (47 kB)
  Preparing metadata (setup.py) ... done
Collecting matplotlib>=3.1.2
  Using cached matplotlib-3.6.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.8 MB)
Collecting numpy>=1.18.1
  Using cached numpy-1.24.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Collecting ponomarenko>=0.0.4.post1
  Using cached ponomarenko-0.0.4.post1.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Collecting rasterio>=1.1.2
  Using cached rasterio-1.3.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (20.9 MB)
Collecting scipy>=1.3.0
  Using cached scipy-1.10.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.4 MB)
Collecting fonttools>=4.22.0
  Using cached fonttools-4.38.0-py3-none-any.whl (965 kB)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting pyparsing>=2.2.1
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting python-dateutil>=2.7
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.4.4-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
Collecting contourpy>=1.0.1
  Using cached contourpy-1.0.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (300 kB)
Collecting packaging>=20.0
  Using cached packaging-23.0-py3-none-any.whl (42 kB)
Collecting attrs
  Using cached attrs-22.2.0-py3-none-any.whl (60 kB)
Collecting certifi
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting click>=4.0
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting affine
  Using cached affine-2.3.1-py2.py3-none-any.whl (16 kB)
Collecting click-plugins
  Using cached click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Requirement already satisfied: setuptools in /home/franchesoni/mine/creations/phd/projects/current/hyperspectral/env_solarium/lib/python3.10/site-packages (from rasterio>=1.1.2->rrn==0.0.1) (59.6.0)
Collecting snuggs>=1.4.1
  Using cached snuggs-1.4.7-py3-none-any.whl (5.4 kB)
Collecting cligj>=0.5
  Using cached cligj-0.7.2-py3-none-any.whl (7.1 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using legacy 'setup.py install' for rrn, since package 'wheel' is not installed.
Using legacy 'setup.py install' for iio, since package 'wheel' is not installed.
Using legacy 'setup.py install' for ponomarenko, since package 'wheel' is not installed.
Installing collected packages: iio, affine, six, pyparsing, Pillow, packaging, numpy, kiwisolver, fonttools, cycler, click, certifi, attrs, snuggs, scipy, python-dateutil, ponomarenko, contourpy, cligj, click-plugins, rasterio, matplotlib, rrn
  Running setup.py install for iio ... done
  Running setup.py install for ponomarenko ... done
  Running setup.py install for rrn ... done
Successfully installed Pillow-9.4.0 affine-2.3.1 attrs-22.2.0 certifi-2022.12.7 click-8.1.3 click-plugins-1.1.1 cligj-0.7.2 contourpy-1.0.7 cycler-0.11.0 fonttools-4.38.0 iio-4 kiwisolver-1.4.4 matplotlib-3.6.3 numpy-1.24.1 packaging-23.0 ponomarenko-0.0.4.post1 pyparsing-3.0.9 python-dateutil-2.8.2 rasterio-1.3.4 rrn-0.0.1 scipy-1.10.0 six-1.16.0 snuggs-1.4.7
```

and finally run the test
`./tests/test.sh `
```
=== Applying ./tests/../rrn/normalization.py with three bands: B02, B03 and B04

Traceback (most recent call last):
  File "/home/franchesoni/mine/creations/phd/projects/current/hyperspectral/rrn-multisensor-multidate/./tests/../rrn/normalization.py", line 36, in <module>
    from rrn.clouds import cloud_masks
  File "/home/franchesoni/mine/creations/phd/projects/current/hyperspectral/env_solarium/lib/python3.10/site-packages/rrn/clouds.py", line 61, in <module>
    def angles(im0, im1, lib_path=load_config()['angles']):
  File "/home/franchesoni/mine/creations/phd/projects/current/hyperspectral/env_solarium/lib/python3.10/site-packages/rrn/clouds.py", line 23, in load_config
    raise FileNotFoundError(
FileNotFoundError: Cannot find lib /home/franchesoni/mine/creations/phd/projects/current/hyperspectral/env_solarium/lib/python3.10/site-packages/rrn/corrsift/libcorrsift.so, please check this path
```
and indeed, in the folder `env_rrn/lib/python3.10/site-packages/rrn` we only have:
```.  ..  __about__.py  clouds.py  contrast.py  corrsift_wrapper.py  keys.py  model_parameters_estimation.py  normalization.py  __pycache__  utils.py```

what am I doing wrong?

**Comment by chlsl** [comment]
The package uses some C code, compiled when installing with pip. Apparently the compilation failed.
First make sure you have all required libraries. You need: libtiff, libpng and libjpeg.
Then reinstall with `pip install -vv .`, so as to get the compilation messages. If it still fails to compile, report the messages you got under `running build`.
